# http://www.appveyor.com/docs/appveyor-yml

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Test against these versions of Node.js.
environment:
  matrix:
    - nodejs_version: "0.12"

install:
  # Typical npm stuff.
  - md C:\nc
  - npm install -g npm@^2
  # hide python so node-gyp won't try to build native extentions
  - rename C:\Python27 Python27hidden
  - npm config set cache C:\nc
  - npm version
  - npm install

test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm run test

version: "{build}"
